# Generated by Django 5.0.3 on 2024-06-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0004_remove_player_player_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='stack',
            field=models.IntegerField(default=100),
        ),
    ]
