# Generated by Django 5.0.3 on 2024-06-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0006_gamestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='street',
            field=models.CharField(default='preflop', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='round_count',
            field=models.IntegerField(default=1),
        ),
    ]
