# Generated by Django 5.0.3 on 2024-06-22 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0007_gamestate_street_alter_gamestate_round_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameState',
        ),
    ]
