# Generated by Django 5.0.3 on 2024-06-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0008_delete_gamestate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='Hero',
        ),
    ]
