# Generated by Django 5.0.3 on 2024-07-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0009_rename_player_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_stack', models.IntegerField(default=150)),
                ('small_blind', models.IntegerField(default=5)),
                ('ante', models.IntegerField(default=0)),
            ],
        ),
    ]
