# Generated by Django 5.0.3 on 2024-07-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0010_gameconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameconfig',
            name='initial_stack',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='small_blind',
            field=models.IntegerField(default=1),
        ),
    ]
