# Generated by Django 5.0.3 on 2024-07-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0012_alter_gameconfig_initial_stack_alter_hero_stack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='stack',
            new_name='initial_stack',
        ),
    ]
