# Generated by Django 5.0.3 on 2024-07-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0013_rename_stack_hero_initial_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='initial_stack',
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='ante',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='initial_stack',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='small_blind',
            field=models.IntegerField(max_length=3),
        ),
    ]
