# Generated by Django 5.0.3 on 2024-07-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0014_remove_hero_initial_stack_alter_gameconfig_ante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='stack',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='ante',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='initial_stack',
            field=models.IntegerField(default=160),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='small_blind',
            field=models.IntegerField(default=1),
        ),
    ]
