# Generated by Django 5.0.3 on 2024-07-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0015_hero_stack_alter_gameconfig_ante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='stack',
        ),
    ]
