# Generated by Django 5.0.3 on 2024-10-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0016_remove_hero_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameconfig',
            name='ante',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='initial_stack',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='small_blind',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
