# Generated by Django 5.0.3 on 2024-03-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hand_history', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PokerHand',
        ),
    ]
