# Generated by Django 5.0.3 on 2024-06-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand_history', '0005_player_stack'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_count', models.IntegerField(default=0)),
            ],
        ),
    ]
